### PR TITLE
Add prismatic joints

### LINKED ISSUE #28: Support prismatic joints
For the goals of one of our internal projects, it would be convenient if ADAM supported prismatic joints. 

cc @Giulero

### PR DESCRIPTION
**Pull request by Giulero**
This PR adds prismatic joints manipulations. Basically I copy-pasted the modification @CarlottaSartore did in a previous pr.

Since we now support 3 different types of joint it might be worth to generalize the joint interface, since the code contains some duplicates. I'll do it (maybe in a separate PR).

I need a urdf of a robot with prismatic joints to test the modifications.

Fixes #28

### CODE REVIEW

**Comment by traversaro** [comment]
> I need a urdf of a robot with prismatic joints to test the modifications.

Probably the easiest thing to do is to start with a trivial one, like https://github.com/robotology/idyntree/blob/master/src/tests/data/twoLinks.urdf but substituting the `continuous` joint with a prismatic one.

**Comment by Giulero** [comment]
Tested with an urdf with prismatic joints! Tests succesful

**Review by CarlottaSartore — APPROVED** [review]
Looks good to me !

**Comment by traversaro** [comment]
cc @VenusPasandi

**Pull request merged**
