### PR TITLE
Set float64 

### PR DESCRIPTION
**Pull request by Giulero**
This PR hopefully fixes "random" failing tests with Jax and Pytorch. 
See:
- https://pytorch.org/docs/stable/notes/numerical_accuracy.html
- https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision

### CODE REVIEW

**Comment by traversaro** [comment]
I tried to apply this in the conda-forge PR (see https://github.com/traversaro/staged-recipes/commit/e20e773c61a3115f8bb6102c30295d6bd8f1b6dc and https://github.com/traversaro/staged-recipes/commit/6d839a1e68d1a5d21139cba069f4c8f20a20c04a) to see if this fixes the failure.

**Comment by traversaro** [comment]
> I tried to apply this in the conda-forge PR (see [traversaro/staged-recipes@e20e773](https://github.com/traversaro/staged-recipes/commit/e20e773c61a3115f8bb6102c30295d6bd8f1b6dc) and [traversaro/staged-recipes@6d839a1](https://github.com/traversaro/staged-recipes/commit/6d839a1e68d1a5d21139cba069f4c8f20a20c04a)) to see if this fixes the failure.

Apparently the failures continue even with this patch: https://github.com/conda-forge/staged-recipes/pull/21894 .

**Comment by Giulero** [comment]
That really mysterious :fearful: 
I don't understand. In `gravity_term`, the only difference with `bias_forces` is that the robot velocity is zero. What can it be?

**Review by traversaro — APPROVED** [review]

**Comment by Giulero** [comment]
Thanks @traversaro!

**Pull request merged**
