### PR TITLE
Add conda-forge CI

### PR DESCRIPTION
**Pull request by traversaro**

### CODE REVIEW

**Comment by traversaro** [comment]
I opened this PR to reprodude the test failures in https://github.com/conda-forge/staged-recipes/pull/21894#issuecomment-1535488061, but unfortunatly I can't, I need to thing more about this.

**Comment by Giulero** [comment]
Hi @traversaro! I don't understand either. `gravity_force` uses the rnea. I would aspect at least also `bias_force` and `coriolis_force` to fail at least.

**Comment by traversaro** [comment]
I was able to reproduce the problem by using the exact same docker image used in conda-forge to build packages. That Docker Image is based on Centos 7, that is rather old, so I guess this could be a Kernel or glibc problem that somehow is interacting with the pytorch/jax/adam stack.

**Comment by Giulero** [comment]
Wow. Thanks a lot @traversaro for the investigation! What can be done?

**Comment by traversaro** [comment]
> Wow. Thanks a lot @traversaro for the investigation! What can be done?

I am trying to understand a bit more. I added a few tests that helped to understand the problem:

| OS   |  Linux Version |  glib version |   Working? |
|:------:|:-------------:|:-------------:|:---------:| 
| CentOS 7 |             |               |     ❌   |
| Ubuntu 16.04         |             |               |      ❌    |
| Ubuntu 18.04 |             |               |   ✅  |
| Ubuntu 20.04         |             |               |  ✅  |
| Ubuntu 22.04         |             |               |  ✅  |

**Comment by traversaro** [comment]
Thanks to Fedora docker images (the Ubuntu one for distros like 16.40 or 17.04 are not working), it is possible to bisect the glibc versions, and it seems that the problem appear for glibc <= 2.25 and disappears for glibc >= 2.26 .

**Comment by traversaro** [comment]
Given that we debugged the problem with glibc <= 2.25, I cleaned up the PR, and re-enabled Windows and macOS tests. I think once CI is happy we can merge, just rember to Squash and merge, as otherwise there are 26 useless commit in the history.

**Comment by traversaro** [comment]
> Given that we debugged the problem with glibc <= 2.25, I cleaned up the PR, and re-enabled Windows and macOS tests. I think once CI is happy we can merge, just rember to Squash and merge, as otherwise there are 26 useless commit in the history.

macOS CI is again angry about gravity tests, something is fishy.

**Comment by traversaro** [comment]
Bingo: the problem was much simpler. The test were using some not initialized memory, as the Twist were initialized as: 
~~~
vb = idyntree.Twist()
~~~
and used if their value was zero, that sometime it was not. The fix is simply to use instead:
~~~
vb = idyntree.Twist.Zero()
~~~

**Comment by traversaro** [comment]
I ported the fix obtained after the debug in https://github.com/ami-iit/ADAM/pull/40, let's close this PR, if necessary I will propose a conda-forge-based CI in a different PR.

**Pull request closed without merging**
